version: 2

# Define common steps all parts of the test workflow use
references:
  ignored-branches: &ignored-branches
    branches:
      ignore:
        - gh-pages

  cache-options: &cache-options
    key: package-cache-{{ .Branch }}-{{ .Revision }}

  shared-test-steps: &shared-test-steps
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: rebuild packages for this node version
          command: npm rebuild
      - run:
          name: display-node-version
          command: node --version
      - run:
          name: display-npm-version
          command: npm --version
      - run:
          name: test
          command: npm test

# Test the common workflow on multiple versions of node
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test-node-v8:
    docker:
      - image: circleci/node:8
      - image: redis:5
    <<: *shared-test-steps

  test-node-v10:
    docker:
      - image: circleci/node:10
      - image: redis:5
    <<: *shared-test-steps

  test-node-v12:
    docker:
      - image: circleci/node:12
      - image: redis:5
    <<: *shared-test-steps

  tests-complete:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: hooray
          command: echo "hooray the tests are complete"

# Run all the tests is parallel
workflows:
  version: 2
  test-all-node-versions:
    jobs:
      - build:
          filters:
            <<: *ignored-branches

      - test-node-v8:
          filters:
            <<: *ignored-branches
          requires:
            - build

      - test-node-v10:
          filters:
            <<: *ignored-branches
          requires:
            - build

      - test-node-v12:
          filters:
            <<: *ignored-branches
          requires:
            - build

      - tests-complete:
          filters:
            <<: *ignored-branches
          requires:
            - test-node-v8
            - test-node-v10
            - test-node-v12
